### PR TITLE
Improve accuracy of dew point calculations

### PR DESCRIPTION
**Pull request by lymanepp**
I noticed that the dew point calculations were off a bit. I ported my C# implementation to Groovy for better accuracy.

Thank you for providing this excellent driver! I am going to get good use out of it.

### CODE REVIEW

**Comment by mircolino** [comment]
Thank you so much! This looks much better than the formula I found on Wiki. 👍

**Comment by lymanepp** [comment]
Hi Mirco,

Here's an image if you care to use it in your documentation. My HTML 
template is:

<i class="ewi-temperature"></i>${temperature} &deg;F<br><i 
class="ewi-humidity"></i>${humidity} %<br><i 
class="ewi-dew"></i>${dewPoint}<br><i 
class="ewi-heat"></i>${simmerIndex}<br><p 
style="color:#${simmerColor}">${simmerDanger}</p>

**Comment by mircolino** [comment]
Hi Lyman,

Thank you for the template!

I added it to the repository in both °F and °C. The number is 6.
I also updated the template html page
<https://github.com/mircolino/ecowitt/blob/master/templates.md>.


Cheers,

---Mirco.

**Comment by lymanepp** [comment]
Thank you!

**Pull request merged**
